<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="74140" started-at="2019-08-15T07:18:23Z" finished-at="2019-08-15T07:19:37Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="74140" started-at="2019-08-15T07:18:23Z" finished-at="2019-08-15T07:19:37Z">
      <class name="com.maven.TestCases.Test1">
        <test-method status="PASS" signature="testSetup()[pri:0, instance:com.maven.TestCases.Test1@1604f19]" name="testSetup" is-config="true" duration-ms="57023" started-at="2019-08-15T12:48:23Z" finished-at="2019-08-15T12:49:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetup -->
        <test-method status="FAIL" signature="demo()[pri:0, instance:com.maven.TestCases.Test1@1604f19]" name="demo" duration-ms="12" started-at="2019-08-15T12:49:20Z" finished-at="2019-08-15T12:49:20Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.maven.PageObjects.LoginPage.LoginApplication(LoginPage.java:20)
	at com.maven.TestCases.Test1.demo(Test1.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demo -->
        <test-method status="PASS" signature="testTearDown()[pri:0, instance:com.maven.TestCases.Test1@1604f19]" name="testTearDown" is-config="true" duration-ms="16876" started-at="2019-08-15T12:49:20Z" finished-at="2019-08-15T12:49:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTearDown -->
      </class> <!-- com.maven.TestCases.Test1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
